### ISSUE TITLE
Galaga & Democore's M2M-measured DY diverges from ASCAL's DY

### ISSUE THREAD

**Issue by sy2002** [sy2002/MiSTer2MEGA65#11]
The democore's M2M-measured DY diverge from ASCAL's DY as shown here:

![serial-output-screenshot](https://github.com/sy2002/MiSTer2MEGA65/assets/6825267/e8f37044-983e-46d1-be5f-d8b11c24ba86)

**Comment by sy2002** [comment]
**Galaga also shows the divergence**

<img width="565" alt="grafik" src="https://github.com/sy2002/MiSTer2MEGA65/assets/6825267/3f35781c-3f80-4fe3-a279-94730b3995cb">

**The C64 core seems to work**

**Comment by MJoergen** [comment]
Fixed in commit 9a070f2
