### ISSUE TITLE
Proof-read new Wiki articles

### ISSUE THREAD

**Issue by sy2002** [sy2002/MiSTer2MEGA65#14]
Please proof-read these two articles:

https://github.com/sy2002/MiSTer2MEGA65/wiki/Fatal-Errors

https://github.com/sy2002/MiSTer2MEGA65/wiki/Shell-memory-layout

**Feel free to not only edit for spelling and grammar but also for clarity.**

Close this issue when done.

**Comment by MJoergen** [comment]
Done.
