### ISSUE TITLE
Galaga Framebuffer for M2M?

### ISSUE THREAD

**Issue by sy2002** [sy2002/MiSTer2MEGA65#15]
The Framebuffer you did for Galaga looks interesting.

Is it generic enough to become an official "member" of M2M? An optional tool that is helpful for cores like Galaga - or the GameBoy (which is not yet ported to M2M) and which render to framebuffers?

If so, please merge/migrate to M2M.

**Comment by MJoergen** [comment]
Yes, this is fit for the M2M.

**Comment by MJoergen** [comment]
Added files in commit 4ff1789

**Comment by MJoergen** [comment]
Question: Should the democore be updated to make use of this frame_buffer ?

**Comment by sy2002** [comment]
I propose not to do this as it max the demo core more complex.
