### ISSUE TITLE
Board-dependent HyperRAM phases

### ISSUE THREAD

**Issue by sy2002** [sy2002/MiSTer2MEGA65#35]
Labeled as V2.0.0 and needed for the C64 core V5.1:

We found that each board revision seems to need its own HyperRAM phase. We need to experimentally confirm the right phases for R4 and R5 and we stick to the known-good phase for R3/R3A.

**Comment by MJoergen** [comment]
Fixed in commit d44a3a3

**Comment by sy2002** [comment]
@MJoergen Were we already done finding a stable Phase for R4? Curious to learn more about your thought process.

**Comment by MJoergen** [comment]
The ability to have a constant phase shift different for each board revision is now implemented.

The actual value chosen for R4 (and R5) is a "good enough" value based on the recent feedback in the Skype channel.

However, I'm planning on doing a more systematic test, using this branch: https://github.com/MJoergen/HyperRAM/tree/mfj_phase_shift
