### ISSUE TITLE
R5 board: Avoid squeaking sound due to the operation of 2 new power supplies MP8869S

### ISSUE THREAD

**Issue by sy2002** [sy2002/MiSTer2MEGA65#37]
This info came via the R5 board email discussion group:

Trenz produced and tested first R5 prototypes.

During tests, we discovered a squeaking sound due to the operation of 2 new power supplies MP8869S. 
As we found out, this is due to the LLM operating mode, which automatically switches to PWM mode when a certain power consumption threshold is reached.
See description of Reg01 SysCntlreg1 in the datasheet. Unfortunately there is no OTP memory for reconfiguration on production.

![grafik](https://github.com/sy2002/MiSTer2MEGA65/assets/6825267/5e229310-f0e2-4fcf-8eee-1435712aed05)

Paul asked:

Regarding the power supply noise, am I correct in assuming that we can make the FPGA bitstream control those to select the silent mode of operation?

Answer from Vadim:

That's correct. The FPGA is connected to power supplies via the I2C bus.

**Comment by MJoergen** [comment]
This has been fixed.
